//
//  TestData.swift
//  FollowersTests
//
//  Created by Eduard Ptushko on 21.02.2024.
//

import Foundation

let testDataFollowers: Data = """
[
  {
    "login": "tkersey",
    "id": 217,
    "node_id": "MDQ6VXNlcjIxNw==",
    "avatar_url": "https://avatars.githubusercontent.com/u/217?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tkersey",
    "html_url": "https://github.com/tkersey",
    "followers_url": "https://api.github.com/users/tkersey/followers",
    "following_url": "https://api.github.com/users/tkersey/following{/other_user}",
    "gists_url": "https://api.github.com/users/tkersey/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tkersey/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tkersey/subscriptions",
    "organizations_url": "https://api.github.com/users/tkersey/orgs",
    "repos_url": "https://api.github.com/users/tkersey/repos",
    "events_url": "https://api.github.com/users/tkersey/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tkersey/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "rickmzp",
    "id": 1114,
    "node_id": "MDQ6VXNlcjExMTQ=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1114?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rickmzp",
    "html_url": "https://github.com/rickmzp",
    "followers_url": "https://api.github.com/users/rickmzp/followers",
    "following_url": "https://api.github.com/users/rickmzp/following{/other_user}",
    "gists_url": "https://api.github.com/users/rickmzp/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rickmzp/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rickmzp/subscriptions",
    "organizations_url": "https://api.github.com/users/rickmzp/orgs",
    "repos_url": "https://api.github.com/users/rickmzp/repos",
    "events_url": "https://api.github.com/users/rickmzp/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rickmzp/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Cordobo",
    "id": 1158,
    "node_id": "MDQ6VXNlcjExNTg=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1158?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Cordobo",
    "html_url": "https://github.com/Cordobo",
    "followers_url": "https://api.github.com/users/Cordobo/followers",
    "following_url": "https://api.github.com/users/Cordobo/following{/other_user}",
    "gists_url": "https://api.github.com/users/Cordobo/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Cordobo/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Cordobo/subscriptions",
    "organizations_url": "https://api.github.com/users/Cordobo/orgs",
    "repos_url": "https://api.github.com/users/Cordobo/repos",
    "events_url": "https://api.github.com/users/Cordobo/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Cordobo/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Krishna",
    "id": 1164,
    "node_id": "MDQ6VXNlcjExNjQ=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1164?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Krishna",
    "html_url": "https://github.com/Krishna",
    "followers_url": "https://api.github.com/users/Krishna/followers",
    "following_url": "https://api.github.com/users/Krishna/following{/other_user}",
    "gists_url": "https://api.github.com/users/Krishna/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Krishna/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Krishna/subscriptions",
    "organizations_url": "https://api.github.com/users/Krishna/orgs",
    "repos_url": "https://api.github.com/users/Krishna/repos",
    "events_url": "https://api.github.com/users/Krishna/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Krishna/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "abisani",
    "id": 1954,
    "node_id": "MDQ6VXNlcjE5NTQ=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1954?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/abisani",
    "html_url": "https://github.com/abisani",
    "followers_url": "https://api.github.com/users/abisani/followers",
    "following_url": "https://api.github.com/users/abisani/following{/other_user}",
    "gists_url": "https://api.github.com/users/abisani/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/abisani/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/abisani/subscriptions",
    "organizations_url": "https://api.github.com/users/abisani/orgs",
    "repos_url": "https://api.github.com/users/abisani/repos",
    "events_url": "https://api.github.com/users/abisani/events{/privacy}",
    "received_events_url": "https://api.github.com/users/abisani/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "cheeaun",
    "id": 2296,
    "node_id": "MDQ6VXNlcjIyOTY=",
    "avatar_url": "https://avatars.githubusercontent.com/u/2296?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/cheeaun",
    "html_url": "https://github.com/cheeaun",
    "followers_url": "https://api.github.com/users/cheeaun/followers",
    "following_url": "https://api.github.com/users/cheeaun/following{/other_user}",
    "gists_url": "https://api.github.com/users/cheeaun/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/cheeaun/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/cheeaun/subscriptions",
    "organizations_url": "https://api.github.com/users/cheeaun/orgs",
    "repos_url": "https://api.github.com/users/cheeaun/repos",
    "events_url": "https://api.github.com/users/cheeaun/events{/privacy}",
    "received_events_url": "https://api.github.com/users/cheeaun/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "chrisledet",
    "id": 4164,
    "node_id": "MDQ6VXNlcjQxNjQ=",
    "avatar_url": "https://avatars.githubusercontent.com/u/4164?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/chrisledet",
    "html_url": "https://github.com/chrisledet",
    "followers_url": "https://api.github.com/users/chrisledet/followers",
    "following_url": "https://api.github.com/users/chrisledet/following{/other_user}",
    "gists_url": "https://api.github.com/users/chrisledet/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/chrisledet/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/chrisledet/subscriptions",
    "organizations_url": "https://api.github.com/users/chrisledet/orgs",
    "repos_url": "https://api.github.com/users/chrisledet/repos",
    "events_url": "https://api.github.com/users/chrisledet/events{/privacy}",
    "received_events_url": "https://api.github.com/users/chrisledet/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "iamteem",
    "id": 4166,
    "node_id": "MDQ6VXNlcjQxNjY=",
    "avatar_url": "https://avatars.githubusercontent.com/u/4166?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/iamteem",
    "html_url": "https://github.com/iamteem",
    "followers_url": "https://api.github.com/users/iamteem/followers",
    "following_url": "https://api.github.com/users/iamteem/following{/other_user}",
    "gists_url": "https://api.github.com/users/iamteem/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/iamteem/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/iamteem/subscriptions",
    "organizations_url": "https://api.github.com/users/iamteem/orgs",
    "repos_url": "https://api.github.com/users/iamteem/repos",
    "events_url": "https://api.github.com/users/iamteem/events{/privacy}",
    "received_events_url": "https://api.github.com/users/iamteem/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "rdouble",
    "id": 4649,
    "node_id": "MDQ6VXNlcjQ2NDk=",
    "avatar_url": "https://avatars.githubusercontent.com/u/4649?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rdouble",
    "html_url": "https://github.com/rdouble",
    "followers_url": "https://api.github.com/users/rdouble/followers",
    "following_url": "https://api.github.com/users/rdouble/following{/other_user}",
    "gists_url": "https://api.github.com/users/rdouble/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rdouble/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rdouble/subscriptions",
    "organizations_url": "https://api.github.com/users/rdouble/orgs",
    "repos_url": "https://api.github.com/users/rdouble/repos",
    "events_url": "https://api.github.com/users/rdouble/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rdouble/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "tonyarnold",
    "id": 4802,
    "node_id": "MDQ6VXNlcjQ4MDI=",
    "avatar_url": "https://avatars.githubusercontent.com/u/4802?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tonyarnold",
    "html_url": "https://github.com/tonyarnold",
    "followers_url": "https://api.github.com/users/tonyarnold/followers",
    "following_url": "https://api.github.com/users/tonyarnold/following{/other_user}",
    "gists_url": "https://api.github.com/users/tonyarnold/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tonyarnold/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tonyarnold/subscriptions",
    "organizations_url": "https://api.github.com/users/tonyarnold/orgs",
    "repos_url": "https://api.github.com/users/tonyarnold/repos",
    "events_url": "https://api.github.com/users/tonyarnold/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tonyarnold/received_events",
    "type": "User",
    "site_admin": false
  }
]
""".data(using: .utf8)!

let testUser: Data = """
{
  "login": "goz",
  "id": 20762,
  "node_id": "MDQ6VXNlcjIwNzYy",
  "avatar_url": "https://avatars.githubusercontent.com/u/20762?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/goz",
  "html_url": "https://github.com/goz",
  "followers_url": "https://api.github.com/users/goz/followers",
  "following_url": "https://api.github.com/users/goz/following{/other_user}",
  "gists_url": "https://api.github.com/users/goz/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/goz/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/goz/subscriptions",
  "organizations_url": "https://api.github.com/users/goz/orgs",
  "repos_url": "https://api.github.com/users/goz/repos",
  "events_url": "https://api.github.com/users/goz/events{/privacy}",
  "received_events_url": "https://api.github.com/users/goz/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Ahmad Gozali",
  "company": null,
  "blog": "goza.li",
  "location": "Singapore",
  "email": null,
  "hireable": null,
  "bio": "Know very little except how to google",
  "twitter_username": null,
  "public_repos": 85,
  "public_gists": 28,
  "followers": 134,
  "following": 64,
  "created_at": "2008-08-15T08:05:36Z",
  "updated_at": "2024-02-19T14:24:14Z"
}
""".data(using: .utf8)!

let testInvalidUser: Data = """
{
  "login": 1,
  "id": 20762,
  "node_id": "MDQ6VXNlcjIwNzYy",
  "avatar_url": "https://avatars.githubusercontent.com/u/20762?v=4",
  "gravatar_id": "",
}
""".data(using: .utf8)!

let testEmptyData: Data = """

""".data(using: .utf8)!
